server:
  http_listen_port: 3200
distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:
ingester:
  trace_idle_period: 10s
  max_block_bytes: 100000000
compactor:
  compaction:
    block_retention: 168h
storage:
  trace:
    backend: local
    local:
      path: /var/tempo
